### ISSUE TITLE
Publish a new release

### ISSUE THREAD

**Issue by waldyrious** [luishdez/flat-flags#13]
Not sure how relevant this is, but since there's already been one release, I think it would make sense to tag and publish a new one incorporating the [changes that have been added since then](https://github.com/wobblecode/flat-flags/compare/v1.0.1...master), particularly those of #11 and #12 :slightly_smiling_face: (And maybe mention e34919f340c19c7b7c89c5c44fe9c6d31106ce24 as well?)

**Comment by luishdez** [comment]
Sure. @waldyrious I agree.
